# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIn28NlVkoo9Rwawu44tUnCIkIEfQ50Y
"""

import pandas as pd

# c 1. DataFrame Yaratish
data = {
    'Ism' : ['Abdulbosid', 'Jahongir','Iqboljon'],
    'Yoshi' : [ 18, 20, 19 ],
    'Shahar' : ['Andijon','Yangiqorg`on','Buvayda'],
}
df=pd.DataFrame(data)
# 2. /Ma'lumotlarni ko'rish
print(df)
# 3. Filtrlash
young_people = df[df['Yoshi']< 30]
print(" 30 yoshdan kichiklar:\n", young_people)
# 4. O'zgartirish
df['Yoshi'] +=1 # Har bir shaxsning yoshini 1 ga oshirish
print('yangilangan DataFrame:\n', df)
# 5. CSV formatda saqlash
df.to_cav('data,csv', index=False)